---

#
# Common variables
#

###
# Specify the Python interpreter.
ansible_python_interpreter: '/usr/bin/python3'
###
# Enable SSH pipelining.
ansible_ssh_pipelining: True
###
# Define the default SSH common arguments.
ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=accept-new'

###
# Determine if Ansible debug is currently enabled.
ansible_debug_enabled: "{{ (lookup('env','ANSIBLE_DEBUG') | bool) or false }}"
