---

#
# Additional defaults that can be provided with environment vars
#

###
# This variable configure if Openshift will be deployed.
openshift_deploy: "{{ (lookup('env','KUBEINIT_COMMON_OPENSHIFT_DEPLOY') | bool) or false }}"

###
# Certificate default country.
certificate_country: "{{ lookup('env','KUBEINIT_COMMON_CERTIFICATE_COUNTRY') or 'US' }}"

###
# Certificate default state.
certificate_state: "{{ lookup('env','KUBEINIT_COMMON_CERTIFICATE_STATE') or 'MyState' }}"

###
# Certificate default locality.
certificate_locality: "{{ lookup('env','KUBEINIT_COMMON_CERTIFICATE_LOCALITY') or 'MyCity' }}"

###
# Certificate default organization.
certificate_organization: "{{ lookup('env','KUBEINIT_COMMON_CERTIFICATE_ORGANIZATION') or 'MyCompany' }}"

###
# Certificate default OU.
certificate_organizational_unit: "{{ lookup('env','KUBEINIT_COMMON_CERTIFICATE_ORGANIZATIONAL_UNIT') or 'MyDepartment' }}"

###
# Default public DNS.
dns_public: "{{ lookup('env','KUBEINIT_COMMON_DNS_PUBLIC') or '1.1.1.1' }}"

###
# Default SSH key type.
ssh_keytype: "{{ lookup('env','KUBEINIT_COMMON_SSH_KEYTYPE') or 'rsa' }}"
