---
# Copyright kubeinit contributors
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


# All variables intended for modification should be placed in this file.

# All variables within this role should have a prefix of "kubeinit_okd_"
kubeinit_okd_debug: "{{ (ansible_verbosity | int) >= 2 | bool }}"
kubeinit_okd_hide_sensitive_logs: true

kubeinit_okd_pod_cidr: 10.100.0.0/14
kubeinit_okd_service_cidr: 172.30.0.0/16

kubeinit_okd_wait_for_cluster_to_converge: True

###########################################
# If you need to deploy openshift instead #
# This will override the OKD deployment   #
###########################################
kubeinit_okd_openshift_deploy: "{{ kubeinit_common_openshift_deploy }}"
kubeinit_okd_openshift_pullsecret: "{{ kubeinit_common_openshift_pullsecret }}"
kubeinit_okd_openshift_registry_token_cloud_openshift_com: "THIS_IS_AN_EXAMPLE_TOKEN_FOR_CLOUD_OPENSHIFT_COM"
kubeinit_okd_openshift_registry_token_quay_io: "THIS_IS_AN_EXAMPLE_TOKEN_FOR_QUAY_IO"
kubeinit_okd_openshift_registry_token_registry_connect_redhat_com: "THIS_IS_AN_EXAMPLE_TOKEN_FOR_CONNECT_REDHAT_COM"
kubeinit_okd_openshift_registry_token_registry_redhat_io: "THIS_IS_AN_EXAMPLE_TOKEN_FOR_REDHAT_IO"
kubeinit_okd_openshift_registry_token_email: "this_is_an_example_email@example.com"

################################################
# Otherwise we will use the following defaults #
################################################

kubeinit_okd_registry: quay.io
kubeinit_okd_registry_organization_aux: "{% if ( kubeinit_okd_openshift_deploy | default(False) ) %}
                                             openshift-release-dev
                                         {% else %}
                                             openshift
                                         {% endif %}"
kubeinit_okd_registry_organization: "{{ kubeinit_okd_registry_organization_aux | replace(' ','') }}"

kubeinit_okd_registry_repository_aux: "{% if ( kubeinit_okd_openshift_deploy | default(False) ) %}
                                           ocp-release
                                       {% else %}
                                           okd
                                       {% endif %}"
kubeinit_okd_registry_repository: "{{ kubeinit_okd_registry_repository_aux | replace(' ','') }}"

###########################################################################
# Replace 4.7.18 with the OpenShift release you will like to deploy, or   #
# 4.7.0-0.okd-2021-06-19-191547 with the choosen OKD release.             #
###########################################################################
kubeinit_okd_registry_release_tag_aux: "{% if ( kubeinit_okd_openshift_deploy | default(False) ) %}
                                              4.7.18
                                        {% else %}
                                              4.8.0-0.okd-2021-10-01-221835
                                        {% endif %}"
kubeinit_okd_registry_release_tag: "{{ kubeinit_okd_registry_release_tag_aux | replace(' ','') }}"

kubeinit_okd_registry_release_tag_major: "{{ kubeinit_okd_registry_release_tag.split('.')[0] }}"
kubeinit_okd_registry_release_tag_minor: "{{ kubeinit_okd_registry_release_tag.split('.')[1] }}"
kubeinit_okd_registry_release_tag_rev: "{{ kubeinit_okd_registry_release_tag.split('.')[2] }}"

kubeinit_okd_registry_release_url_aux: "{% if ( kubeinit_okd_openshift_deploy | default(False) ) %}
                                           https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ kubeinit_okd_registry_release_tag }}/release.txt
                                       {% else %}
                                           https://api.github.com/repos/openshift/okd/releases/tags/{{ kubeinit_okd_registry_release_tag }}
                                       {% endif %}"
kubeinit_okd_registry_release_url: "{{ kubeinit_okd_registry_release_url_aux | replace(' ','') }}"

# The space after the first single quote is required, do not remove
# Something in Ansible appears to be recognizing this as valid Python,
# so it's getting transformed into a Python list and then serialized
# using Python's str(), which is why we end up with the single-quoted values.
kubeinit_okd_registry_pullsecret: '  { "auths": {} }'
kubeinit_okd_registry_pullsecret_empty: '  { "auths": {} }'

kubeinit_okd_dependencies_client_aux: "{% if ( kubeinit_okd_openshift_deploy | default(False) ) %}
                                          https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ kubeinit_okd_registry_release_tag }}/openshift-client-linux-{{ kubeinit_okd_registry_release_tag }}.tar.gz
                                       {% else %}
                                          https://github.com/openshift/okd/releases/download/{{ kubeinit_okd_registry_release_tag }}/openshift-client-linux-{{ kubeinit_okd_registry_release_tag }}.tar.gz
                                       {% endif %}"

kubeinit_okd_dependencies_installer_aux: "{% if ( kubeinit_okd_openshift_deploy | default(False) ) %}
                                              https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ kubeinit_okd_registry_release_tag }}/openshift-install-linux-{{ kubeinit_okd_registry_release_tag }}.tar.gz
                                          {% else %}
                                              https://github.com/openshift/okd/releases/download/{{ kubeinit_okd_registry_release_tag }}/openshift-install-linux-{{ kubeinit_okd_registry_release_tag }}.tar.gz
                                          {% endif %}"

kubeinit_okd_dependencies:
  client: "{{ kubeinit_okd_dependencies_client_aux | replace(' ','') }}"
  installer: "{{ kubeinit_okd_dependencies_installer_aux | replace(' ','') }}"

kubeinit_okd_fcos_release: "34.20210904.3.0"
kubeinit_okd_rhcos_release: "4.8.2"
kubeinit_okd_rhcos_release_major_minor: "{{ kubeinit_okd_rhcos_release.split('.')[0] }}.{{ kubeinit_okd_rhcos_release.split('.')[1] }}"

kubeinit_okd_coreos_images:
  fcos:
    uri: "https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/{{ kubeinit_okd_fcos_release }}/x86_64/"
    kernel: "fedora-coreos-{{ kubeinit_okd_fcos_release }}-live-kernel-x86_64"
    initrd: "fedora-coreos-{{ kubeinit_okd_fcos_release }}-live-initramfs.x86_64.img"
    raw: "fedora-coreos-{{ kubeinit_okd_fcos_release }}-metal.x86_64.raw.xz"
    sig: "fedora-coreos-{{ kubeinit_okd_fcos_release }}-metal.x86_64.raw.xz.sig"
    rootfs: "fedora-coreos-{{ kubeinit_okd_fcos_release }}-live-rootfs.x86_64.img"
  rhcos:
    uri: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/{{ kubeinit_okd_rhcos_release_major_minor }}/{{ kubeinit_okd_rhcos_release }}/"
    kernel: "rhcos-{{ kubeinit_okd_rhcos_release }}-x86_64-live-kernel-x86_64"
    initrd: "rhcos-{{ kubeinit_okd_rhcos_release }}-x86_64-live-initramfs.x86_64.img"
    raw: "rhcos-{{ kubeinit_okd_rhcos_release }}-x86_64-metal.x86_64.raw.gz"
    sig: ""
    rootfs: rhcos-{{ kubeinit_okd_rhcos_release }}-x86_64-live-rootfs.x86_64.img
