---
# Copyright kubeinit.com
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

##
## Cleanup tasks
##
- name: Cleanup the environment
  block:

    ##
    ## Clean networks
    ##

    - name: Destroy deployment networks
      community.libvirt.virt_net:
        command: destroy
        name: "{{ item.name }}"
      with_items: "{{ kubeinit_libvirt_cluster_nets }}"
      ignore_errors: true
      when: kubeinit_libvirt_destroy_nets|bool and not kubeinit_libvirt_multicluster_keep_predefined_networks

    - name: Undefine deployment networks
      community.libvirt.virt_net:
        command: undefine
        name: "{{ item.name }}"
      with_items: "{{ kubeinit_libvirt_cluster_nets }}"
      ignore_errors: true
      when: kubeinit_libvirt_destroy_nets|bool and not kubeinit_libvirt_multicluster_keep_predefined_networks

    ##
    ## Clean VMs
    ##

    - name: Destroy vms
      community.libvirt.virt:
        name: "{{ item }}"
        command: destroy
      with_items: "{{ groups['all_nodes'] }}"
      ignore_errors: true

    - name: Undefine vms
      community.libvirt.virt:
        name: "{{ item }}"
        command: undefine
      with_items: "{{ groups['all_nodes'] }}"
      ignore_errors: true

    - name: Remove VMs storage
      ansible.builtin.file:
        state: absent
        path: "{{ kubeinit_libvirt_target_image_dir }}/{{ item }}.qcow2"
      with_items: "{{ groups['all_nodes'] }}"

    ##
    ## Clean folders
    ##

    - name: Clean directories for config files per node
      ansible.builtin.file:
        state: absent
        path: "{{ kubeinit_libvirt_hypervisor_tmp_dir }}/{{ item }}/"
      with_items: "{{ groups['all_nodes'] }}"


    ##
    ## Clean OVN resources
    ##
    - name: Clean OVN/OVS resources
      ansible.builtin.shell: |
        ovs-vsctl del-br br-int || true
        ovs-vsctl del-br br-ex || true
        ovs-vsctl del-br kiextbr0 || true
        ovn-nbctl ls-del sw0 || true
        ovn-nbctl ls-del sw1 || true
        ovn-nbctl lr-del lr0 || true
        ovn-nbctl ls-del public || true
        ip route del {{ kubeinit_inventory_network_net }}/{{ kubeinit_inventory_network_cidr }} via 172.16.0.1 dev br-ex || true
      ignore_errors: true
      changed_when: false

    ##
    ## Clean keys
    ##

    - name: check if /root/.ssh/known_hosts exists
      ansible.builtin.stat:
        path: /root/.ssh/known_hosts
      register: known_hosts_file

    - name: Reset ssh keys in hypervisor
      ansible.builtin.shell: |
        ssh-keygen -R  {{ item }}
        ssh-keygen -R  {{ item }}.{{ kubeinit_inventory_cluster_domain }}
        ssh-keygen -R  {{ hostvars[item].ansible_host }}
      with_items: "{{ groups['all_nodes'] }}"
      when: known_hosts_file.stat.exists | bool
      ignore_errors: true
      changed_when: false

    - name: reset local ssh keys
      become: no
      delegate_to: localhost
      ansible.builtin.shell: |
        ssh-keygen -R  {{ item }}
        ssh-keygen -R  {{ item }}.{{ kubeinit_inventory_cluster_domain }}
        ssh-keygen -R  {{ hostvars[item].ansible_host }}
      ignore_errors: true
      with_items: "{{ groups['all_nodes'] }}"
      changed_when: false

    - name: Delete keys in ~/.ssh/known_hosts
      ansible.builtin.lineinfile:
        dest: ~/.ssh/known_hosts
        state: absent
        regexp: '{{ hostvars[item].ansible_host }}'
      with_items: "{{ groups['all_nodes'] }}"

    - name: get the IP
      become: no
      delegate_to: localhost
      ansible.builtin.command: hostname --ip-address
      register: local_initiator_ip
      changed_when: "local_initiator_ip.rc == 0"

    - name: Set up the local IP
      ansible.builtin.set_fact:
        kubeinit_libvirt_initiator_ip={{ local_initiator_ip.stdout }}
