---
# Copyright kubeinit.com
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Verify that nodes are up before continuing
  block:
    - name: "make sure we can execute remote commands in {{ kubeinit_deployment_node_name }} before continue"
      ansible.builtin.shell: |
        set -o pipefail
        ssh \
            -o ConnectTimeout=5 \
            -o BatchMode=yes \
            -o StrictHostKeyChecking=no \
            root@{{ hostvars[kubeinit_deployment_node_name].ansible_host }} 'echo connected' || true
      args:
        executable: /bin/bash
      register: cmd_boot_ok_res
      retries: 30
      delay: 10
      until: "'connected' in cmd_boot_ok_res.stdout"
      delegate_to: "{{ kubeinit_bastion_host }}"

    - name: wait for {{ kubeinit_deployment_node_name }} to boot
      ansible.builtin.wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
      delegate_to: "{{ hostvars[kubeinit_deployment_node_name].ansible_host }}"
  tags:
    - provision_libvirt
