---
# defaults file for installer
cache_enabled: false
provision_cache_store: "{{ ansible_env.HOME }}/rhcos_image_cache/"
registry_port_container: 5000
registry_port: "{{ registry_port_container }}"
registry_dir: /opt/registry
install_config_appends_file: install-config-appends.yml
registry_auth_file: registry-auths.json
webserver_caching_port: "{{ webserver_caching_port_container }}"
webserver_caching_port_container: 8081
registry_creation: true
url_passed: false
httpd_cache_files: "{{ provision_cache_store }}httpd/"
disconnected_registry_user: dummy
disconnected_registry_password: dummy
disconnected_installer: true
