---
# Copyright kubeinit.com
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Deploy the cluster nodes
  ansible.builtin.include_role:
    name: "../../roles/kubeinit_libvirt"
    tasks_from: 60_k8s_deploy_nodes.yml
    public: yes
  with_items:
    - "{{ groups['all_nodes'] | list }}"
  loop_control:
    loop_var: cluster_role_item
  vars:
    kubeinit_deployment_node_name: "{{ cluster_role_item }}"

- name: Configure the cluster service node
  ansible.builtin.include_role:
    name: "../../roles/kubeinit_eks"
    tasks_from: 10_configure_service_nodes.yml
    public: yes
  with_items:
    - "{{ groups['all_service_nodes'] | list }}"
  loop_control:
    loop_var: cluster_role_item
  vars:
    kubeinit_deployment_node_name: "{{ cluster_role_item }}"
    kubeinit_deployment_role: service

- name: Configure the cluster common config
  ansible.builtin.include_role:
    name: "../../roles/kubeinit_eks"
    tasks_from: 20_configure_common.yml
    public: yes
  with_items:
    - "{{ groups['all_master_nodes'] + groups['all_worker_nodes'] | list }}"
  loop_control:
    loop_var: cluster_role_item
  vars:
    kubeinit_deployment_node_name: "{{ cluster_role_item }}"

- name: Configure the cluster master nodes
  ansible.builtin.include_role:
    name: "../../roles/kubeinit_eks"
    tasks_from: 30_configure_master_nodes.yml
    public: yes
  with_items:
    - "{{ groups['all_master_nodes'] | list }}"
  loop_control:
    loop_var: cluster_role_item
  vars:
    kubeinit_deployment_node_name: "{{ cluster_role_item }}"
    kubeinit_deployment_role: master

- name: Configure the cluster worker nodes
  ansible.builtin.include_role:
    name: "../../roles/kubeinit_eks"
    tasks_from: 40_configure_worker_nodes.yml
    public: yes
  with_items:
    - "{{ groups['all_worker_nodes'] | list }}"
  loop_control:
    loop_var: cluster_role_item
  vars:
    kubeinit_deployment_node_name: "{{ cluster_role_item }}"
    kubeinit_deployment_role: worker

- name: Finish the k8s post deployment tasks
  ansible.builtin.include_role:
    name: "../../roles/kubeinit_eks"
    tasks_from: 50_post_deployment_tasks.yml
    public: yes
  with_items:
    - "{{ groups['all_service_nodes'] | list }}"
  loop_control:
    loop_var: cluster_role_item
  vars:
    kubeinit_deployment_node_name: "{{ cluster_role_item }}"
    kubeinit_deployment_role: service

- name: Deploy EKS images
  ansible.builtin.include_role:
    name: "../../roles/kubeinit_eks"
    tasks_from: 60_deploy_eks_images.yml
    public: yes
  with_items:
    - "{{ groups['all_service_nodes'] | list }}"
  loop_control:
    loop_var: cluster_role_item
  vars:
    kubeinit_deployment_node_name: "{{ cluster_role_item }}"
    kubeinit_deployment_role: service
