---
- name: Start installation process
  block:
    - include_tasks: roles/installer/tasks/10_clean_bootstrap_vm.yml
    - include_tasks: roles/installer/tasks/20_clean_master_worker_vms.yml
      when: virtualized_install
    - include_tasks: roles/installer/tasks/30_create_bootstrap_vm.yml
    - include_tasks: roles/installer/tasks/40_create_master_worker_vms.yml
      when: virtualized_install
    - include_tasks: roles/installer/tasks/50_create_haproxy.yml
      when: virtualized_install
    - include_tasks: roles/installer/tasks/60_wait_for_bootstrap.yml      
  tags: installer
