---
- name: Get COMMIT_ID
  shell: |
    /usr/local/bin/openshift-baremetal-install version | grep '^built from commit' | awk '{print $4}'
  register: commit_id

- name: Get the URLs
  set_fact:
    offline_url: "{{ webserver_url }}/{{ version }}/rhcos.json"
    online_url: "https://raw.githubusercontent.com/openshift/installer/{{ commit_id.stdout }}/data/data/rhcos.json"

- name: Get RHCOS JSON File
  uri:
    url: "{{ (disconnected_installer|length == 0 ) | ternary(offline_url, online_url) }}"
    return_content: yes
  until: rhcos_json.status == 200
  retries: 6 # 1 minute (10 * 6)
  delay: 10 # Every 10 seconds
  register: rhcos_json
  delegate_to: "{{ disconnected_installer | ternary(groups['registry_host'][0], groups['provisioner'][0]) }}"

- name: Set Facts for RHCOS_URI and RHCOS_PATH
  set_fact:
    rhcos_uri: "{{ rhcos_json.json | json_query('images.metal.path') }}"
    rhcos_path: "{{ rhcos_json.json | json_query('baseURI') }}"

- name: Get URL of host providing the webserver
  set_fact:
    host_url: "{{ groups['registry_host'][0] }}"

# Ansible didn't like me putting these facts in same task
# separating to get correct value
- name: the host url
  set_fact:
    the_host_url: "{{ host_url }}"

#if i made it this far to create a webserver, one of the hosts needs online access
#if disconnected_installer is true use the registry host as it indeed does have access
#if not true use the provision host but only do that when: the_url.status == 200
- name: Fail when provision host no online access and registry host not creating registry (can't assume access)
  fail:
    msg: A host with online access is required to create cache webserver (provision host or a registry host)
  when:
    - disconnected_installer|length == 0

#SELinux when already has httpd_sys_content_t giving issues changing,thus leaving it the same
#for the provision_cache_store to prevent issues. Also removing ":z" from podman_container for
#provision_cache_store in the later task.
- name: Create {{ provision_cache_store }} and {{ httpd_cache_files }} on host with online access
  file:
    path: "{{ item[0] }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    setype: "{{ item[1] }}"
    mode: '0775'
  with_nested:
    - [ "{{ provision_cache_store }}" , "{{ httpd_cache_files }}" ]
    - [ 'httpd_sys_content_t', '_default' ]
  delegate_to: "{{ groups['registry_host'][0] }}"

- name: Add magic and httpd.conf file to {{ httpd_cache_files }} dir
  template:
    src: "{{ item[0] }}"
    dest: "{{ httpd_cache_files }}/{{ item[1] }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  with_nested:
    - [ 'magic.j2', 'httpd_conf.j2' ]
    - [ 'magic', 'httpd.conf' ]
  delegate_to: "{{ groups['registry_host'][0] }}"

# rhcos_json fact already set in 23_rhcos_image_paths.yaml
- name: Set facts for RHCOS SHA256
  set_fact:
    rhcos_sha256: "{{ rhcos_json.json | json_query('images.metal.sha256') }}"
    rhcos_sha256_unzipped: '{{ rhcos_json.json | json_query(''images.metal."uncompressed-sha256"'') }}'

- name: Download {{ rhcos_uri }} for cache
  get_url:
    url:  "{{ rhcos_path }}{{ rhcos_uri }}"
    dest: "{{ provision_cache_store }}{{ rhcos_uri }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
    setype: httpd_sys_content_t
    checksum: "sha256:{{ rhcos_sha256 }}"
    timeout: 3600
  when: (bootstraposimage is not defined or bootstraposimage|length < 1)
  delegate_to: "{{ groups['registry_host'][0] }}"

  #use the hostname from the inventory to groups[registry][0] or provisioner[0] as the http://URL
  #use a ternary to toggle between the url status
  #use a ternary for the delegate_to
- name: Get URL of host providing the webserver
  set_fact:
    host_url: "{{ groups['registry_host'][0] }}"

- name: Set bootstrap image URL override if not provided by the user
  set_fact:
    bootstraposimage: "http://{{ the_host_url }}:{{ webserver_caching_port }}/{{ rhcos_uri }}?sha256={{ rhcos_sha256_unzipped }}"
  when: bootstraposimage is not defined or bootstraposimage|length < 1
  delegate_to: "{{ groups['registry_host'][0] }}"

- name: Set cluster image URL override if not provided by the user
  set_fact:
    clusterosimage: "http://{{ the_host_url }}:{{ webserver_caching_port }}/{{ rhcos_uri }}?sha256={{ rhcos_sha256 }}"
  when: download_rhcos_image|bool and ( clusterosimage is not defined or clusterosimage|length < 1 )
  delegate_to: "{{ groups['registry_host'][0] }}"

#Leaving SELinux details alone and not using ":z"
#for the provision_cache_store due to issues attempting
#to revert context. Leaving behavior as it was previously
#to avoid breaking other user environments.
- name: Start RHCOS image cache container
  podman_container:
    name: rhcos_image_cache
    image: registry.centos.org/centos/httpd-24-centos7:latest
    state: stopped
    network: host
    volumes:
      - "{{ provision_cache_store }}:/var/www/html"
      - "{{ httpd_cache_files }}:/opt/rh/httpd24/root/etc/httpd/conf:z"
  delegate_to: "{{ groups['registry_host'][0] }}"
  register: rhcos_image_cache_info

- name: Setting facts about container
  set_fact:
    rhcos_image_cache_name: "{{ rhcos_image_cache_info.ansible_facts.podman_container.Name }}"
    rhcos_image_cache_pidfile: "{{ rhcos_image_cache_info.ansible_facts.podman_container.ConmonPidFile }}"

- name: Ensuring container restarts upon reboot
  block:
    - name: Ensure user specific systemd instance are persistent
      command:  |
              /usr/bin/loginctl enable-linger {{ ansible_user }}
    - name: Create systemd user directory
      file:
        path: "{{ ansible_user_dir }}/.config/systemd/user"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0775'

    - name: Copy the systemd service file
      copy:
        content: |
          [Unit]
          Description=Podman container-cache.service
          [Service]
          Restart=on-failure
          ExecStart=/usr/bin/podman start {{ rhcos_image_cache_name }}
          ExecStop=/usr/bin/podman stop -t 10 {{ rhcos_image_cache_name }}
          KillMode=none
          Type=forking
          PIDFile={{ rhcos_image_cache_pidfile }}
          [Install]
          WantedBy=default.target
        dest: "{{ ansible_user_dir }}/.config/systemd/user/container-cache.service"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'

    - name: Reload systemd service
      systemd:
        daemon_reexec: yes
        scope: user
      environment:
        DBUS_SESSION_BUS_ADDRESS: "{{ ansible_env.DBUS_SESSION_BUS_ADDRESS|default('unix:path=/run/user/' +  ansible_effective_user_id|string + '/bus') }}"
    - name: Enable container-cache.service
      systemd:
        name: container-cache.service
        enabled: yes
        scope: user
      environment:
        DBUS_SESSION_BUS_ADDRESS: "{{ ansible_env.DBUS_SESSION_BUS_ADDRESS|default('unix:path=/run/user/' +  ansible_effective_user_id|string + '/bus') }}"
    - name: Start container-cache.service
      systemd:
        name: container-cache.service
        state: started
        scope: user
      environment:
        DBUS_SESSION_BUS_ADDRESS: "{{ ansible_env.DBUS_SESSION_BUS_ADDRESS|default('unix:path=/run/user/' +  ansible_effective_user_id|string + '/bus') }}"
  delegate_to: "{{ groups['registry_host'][0] }}"
