---
# Copyright kubeinit.com
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

#
# Initial config
#

- name: Configure common requirements in guests
  block:
    - name: Force apt-get update
      shell: |
        apt-get update
      changed_when: false

    - name: update packages
      package:
        name: "*"
        state: latest
      register: update_packages

    - name: Enable cloud init
      shell: |
        systemctl enable cloud-init
        systemctl start cloud-init
      changed_when: false

    - name: Reboot immediately after the package update
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0
      when: update_packages is changed

    - name: Wait for the reboot to complete if there was a change.
      wait_for:
        port: 22
        host: "{{ hostvars[kubeinit_deployment_node_name].ansible_host }}"
        search_regex: OpenSSH
        delay: 10
        timeout: 7200
      when: update_packages is changed
      delegate_to: "{{ hostvars[kubeinit_deployment_node_name].target }}"

    - name: install common requirements
      package:
        name: "{{ kubeinit_cdk_common_dependencies }}"
        state: present

    - name: Disable SWAP
      shell: |
        swapoff -a
      changed_when: false

    - name: Resize root partition
      shell: |
        echo 'Reclaim space for root partition'
        growpart /dev/vda 1
        resize2fs /dev/vda1
      changed_when: false

    - name: Install Docker
      shell: |
        apt-get update -y
        apt-get remove docker docker-engine docker.io -y
        apt-get install docker.io -y
        docker --version
      changed_when: false

    - name: Start and enable docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install kubectl
      shell: |
        snap install kubectl --classic
      changed_when: false

  delegate_to: "{{ kubeinit_deployment_node_name }}"
  tags:
    - provision_libvirt
