---
# Copyright kubeinit.com
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Remove resolv file
  file:
    path: /etc/resolv.conf
    state: absent
  delegate_to: "{{ item }}"
  with_items:
    - "{{ groups['all'] | map('regex_search','^((?!hypervisor).)*$') | select('string') | list }}"
  tags:
    - provision_libvirt

- name: Create a symbolic link to the resolv.conf file
  file:
    src: /etc/resolvconf/resolv.conf.d/head
    dest: /etc/resolv.conf
    state: link
  delegate_to: "{{ item }}"
  with_items:
    - "{{ groups['all'] | map('regex_search','^((?!hypervisor).)*$') | select('string') | list }}"
  tags:
    - provision_libvirt

- name: Add info to the resolv.conf
  shell: |
    echo "nameserver {{ kubeinit_inventory_network_gateway }}" > /etc/resolv.conf
  changed_when: false
  delegate_to: "{{ item }}"
  with_items:
    - "{{ groups['all'] | map('regex_search','^((?!hypervisor).)*$') | select('string') | list }}"
  tags:
    - provision_libvirt

- name: Restart the resolvconf service
  service:
    name: "resolvconf"
    state: restarted
    enabled: yes
  delegate_to: "{{ item }}"
  with_items:
    - "{{ groups['all'] | map('regex_search','^((?!hypervisor).)*$') | select('string') | list }}"
  tags:
    - provision_libvirt

- name: Restart the systemd-resolved service
  service:
    name: "systemd-resolved"
    state: restarted
    enabled: yes
  delegate_to: "{{ item }}"
  with_items:
    - "{{ groups['all'] | map('regex_search','^((?!hypervisor).)*$') | select('string') | list }}"
  tags:
    - provision_libvirt

# #
# # Configure NFS
# #
#
# - name: Configure NFS
#   delegate_to: "{{ groups['cdk_service_nodes'][0] }}"
#   # delegate_facts: true
#   import_role:
#     name: ../../roles/kubeinit_nfs
#     tasks_from: main
#   tags:
#     - provision_libvirt
