---
- name: Verify that SSH key for {{ ansible_user }} exists
  stat:
    path: "{{ ansible_user_dir }}/.ssh/id_rsa.pub"
  register: sshkeypath

- name: Get the contents of the ssh key for {{ ansible_user }}
  slurp:
    src: "{{ ansible_user_dir }}/.ssh/id_rsa.pub"
  register: sshkey
  when: sshkeypath.stat.exists == true

- name: Set Fact for the ssh key of {{ ansible_user }}
  set_fact:
    key: "{{ sshkey['content'] | b64decode }}"

- name: Create directory for storing ignition files
  file:
    path: "{{ cluster_config_dir }}/generated_ignition"
    state: directory
    mode: '0755'

- name: Generate ignition file for each of the roles
  template:
    src: "{{ role_path }}/templates/coreos_install.service.j2"
    dest: "{{ cluster_config_dir }}/generated_ignition/final_{{ item}}.ign"
  vars:
    - core_sshKey: "{{ key }}"
    - core_password: "core"
    - device: "{{ devices[item] }}"
    - file_path: "{{ cluster_config_dir }}/{{ item }}.ign"
  with_items:
    - "bootstrap"
    - "master"
    - "worker"
