---
- name: Installer configuration tasks
  block:
    - include_tasks: roles/installer-configuration/tasks/10_configure_install_config.yml
    - include_tasks: roles/installer-configuration/tasks/20_create_manifests.yml
    - include_tasks: roles/installer-configuration/tasks/30_create_ignition.yml
  tags: installer_configuration
