- name: Pulling images required for setting up a Kubernetes cluster
  shell: kubeadm config images pull
  tags:
    - master

- name: Resetting kubeadm
  shell: kubeadm reset -f
  register: output
  tags:
    - master

- name: Initializing Kubernetes cluster
  shell: kubeadm init --apiserver-advertise-address {{ad_addr}} --pod-network-cidr={{cidr_v}}
  register: output
  tags:
    - master

- name: Storing Logs and Generated token for future purpose.
  local_action: copy content={{ output.stdout }} dest=/home/centos/{{ token_file }}
  tags:
    - master

- name: Copying required files
  shell: |
   mkdir -p $HOME/.kube
   sudo cp -f /etc/kubernetes/admin.conf $HOME/.kube/config
   sudo chown $(id -u):$(id -g) $HOME/.kube/config
  tags:
    - master

- name: Install Network Add-on
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  tags:
    - master
