- name: Modprobe ip forward
  shell: |
    modprobe br_netfilter
    echo '1' > /proc/sys/net/ipv4/ip_forward
    mkdir -p /proc/sys/net/bridge/
    echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables
    sysctl -p
  tags:
    - kubernetes_common

- name: Creating a repository file for Kubernetes
  file:
    path: /etc/yum.repos.d/kubernetes.repo
    state: touch
  tags:
    - kubernetes_common

- name: Disable SELinux
  selinux:
    state: disabled
  tags:
    - kubernetes_common

- name: Adding repository details in Kubernetes repo file.
  blockinfile:
    path: /etc/yum.repos.d/kubernetes.repo
    block: |
     [kubernetes]
     name=Kubernetes
     baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
     enabled=1
     gpgcheck=1
     repo_gpgcheck=1
     gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
            https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  tags:
    - kubernetes_common

- name: Installing Dockerce repo
  shell: |
    yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  tags:
    - kubernetes_common

- name: upgrade all packages
  yum:
    name: '*'
    state: latest
  tags:
    - kubernetes_common

- name: install requirements
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - docker-ce
    - kubelet
    - kubeadm
    - kubectl
  tags:
    - kubernetes_common

- name: change to cgroup
  command: sed -i 's#Environment="KUBELET_KUBECONFIG_ARGS=-.*#Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --cgroup-driver=systemd"#g' /usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf
  tags:
    - kubernetes_common

- name: check if check restarted file exists
  stat:
    path: "/tmp/restarted"
  register: kubernetes_node_restarted
  tags:
    - kubernetes_common

- name: Reboot host and wait for it to restart
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  when: kubernetes_node_restarted.stat.exists == false
  tags:
    - kubernetes_common

- name: ensure check file exists
  copy:
    content: ""
    dest: "/tmp/restarted"
    force: no
    group: sys
    owner: root
    mode: 0555
  tags:
    - kubernetes_common
