---
# Copyright kubeinit contributors
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

#
# Deploy the apps
#
- block:
    - name: Deploy the apps
      ansible.builtin.include_role:
        name: kubeinit.kubeinit.kubeinit_apps
        public: yes
  vars:
    kubeinit_deployment_node_name: "{{ kubeinit_provision_service_node }}"
  delegate_to: "{{ kubeinit_deployment_node_name }}"

#
# Configure NFS
#
- block:
    - name: Configure NFS
      ansible.builtin.include_role:
        name: kubeinit.kubeinit.kubeinit_nfs
        public: true
      when: "'nfs' in kubeinit_cluster_hostvars.services"
  vars:
    kubeinit_deployment_node_name: "{{ kubeinit_provision_service_node }}"
  delegate_to: "{{ kubeinit_deployment_node_name }}"

#
# Deploy Submariner
#
- block:
    - name: Deploy Submariner
      ansible.builtin.include_role:
        name: kubeinit.kubeinit.kubeinit_submariner
        public: yes
      vars:
        kubeinit_submariner_is_broker: false
        kubeinit_submariner_is_secondary: true
        kubeinit_submariner_deploy_stable: true
      when: "'submariner' in kubeinit_cluster_hostvars.post_deployment_services | default(False)"
  vars:
    kubeinit_deployment_node_name: "{{ kubeinit_provision_service_node }}"
  delegate_to: "{{ kubeinit_deployment_node_name }}"
