---
- name: Define, Start, Autostart Storage Pool
  block:
    - name: Define Storage Pool for default
      virt_pool:
        command: define
        name: default
        xml: '{{ lookup("template", "dir.xml.j2") }}'

    - name: Start Storage Pool for default
      virt_pool:
        state: active
        name: default

    - name: Autostart Storage Pool for default
      virt_pool:
        autostart: yes
        name: default
  become: yes
  tags: storagepool
