---
- name: Setup clusterconfigs dir
  block:
    - name: Clear config dir (if any, in case this is a re-run)
      file:
        path: "{{ item }}"
        state: absent
      with_items:
      - "{{ cluster_config_dir }}"

    - name: Create config dir
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
      with_items:
      - "{{ cluster_config_dir }}"
