---
driver:
  name: podman

log: true

platforms:
  - name: centos7
    hostname: centos7
    image: centos:7
    dockerfile: Dockerfile
    pkg_extras: python-setuptools
    volumes:
      - /etc/ci/mirror_info.sh:/etc/ci/mirror_info.sh:ro
    easy_install:
      - pip
    environment: &env
      http_proxy: "{{ lookup('env', 'http_proxy') }}"
      https_proxy: "{{ lookup('env', 'https_proxy') }}"
    ulimits: &ulimit
      - host

  - name: centos8
    hostname: centos8
    image: centos:8
    dockerfile: Dockerfile
    pkg_extras: python*-setuptools
    volumes:
      - /etc/ci/mirror_info.sh:/etc/ci/mirror_info.sh:ro
    environment:
      <<: *env
    ulimits: *ulimit

provisioner:
  name: ansible
  log: true
  env:
    ANSIBLE_STDOUT_CALLBACK: yaml

scenario:
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - check
    - verify
    - destroy

verifier:
  name: testinfra
