---
- name: Wait for installer to complete
  command: /usr/local/bin/openshift-baremetal-install --dir={{ cluster_config_dir }} wait-for install-complete --log-level info
  register: result
  retries: 5
  delay: 20
  until: result.rc == 0
  changed_when: "result.rc == 0"

- name: Show message to the customer
  debug:
    msg:
      - "Cluster installation finished. You can now start using the cluster."
      - "Your username is kubeadmin, and your password is {{ lookup('file', cluster_config_dir+'/auth/kubeadmin-password') }}"
      - "Or you can export KUBECONFIG={{ cluster_config_dir }}/auth/kubeconfig"
